### ISSUE TITLE
Review del desafío 🕵🏼 

### ISSUE THREAD

**Issue by tobiasfacello** [brunoken22/Desafio-m4#1]
Buenas noches Bruno, felicidades por haber finalizado el desafío final del módulo 🚀 

No tengo mucho para comentar al respecto, hiciste uso del CMS como se pide en los requisitos para aprobar el desafío lo cual vi bien.
A lo sumo un par de cuestiones más visuales pero nada que no se pueda modificar con el tiempo, sobre todo cuando te toca ir variando tamaños entre diferentes resoluciones de pantalla (si tenes ganas, lo podes revisar).
La única cosa que encontré fue que el título en la página Portfolio dice Servicios:
![image](https://user-images.githubusercontent.com/69740939/204677735-b79d72c4-5b06-4269-856d-888923e7c6ba.png)

Más allá de eso creo que lo demás cumple con lo esperado asi que LGTM, éxitos para el próximo módulo!

**Comment by brunoken22** [comment]
Muchísimas gracias ,lo estaré mejorando
